[project]
name = "ble2ws"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "bleak>=1.0.1",
    "websockets>=15.0.1",
]

[dependency-groups]
dev = [
    "ruff>=0.12.7",
]
